SET NAMES utf8;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nom VARCHAR(30) NOT NULL,
    prenom VARCHAR(30) NOT NULL,
    poste VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    mot_de_passe VARCHAR(100) NOT NULL,
    photo_url VARCHAR(100) DEFAULT NULL,
    photo_alt VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (id),
    UNIQUE KEY email (email)
) ENGINE = INNODB;

LOCK TABLES Users WRITE;

UNLOCK TABLES;



DROP TABLE IF EXISTS Post;


CREATE TABLE IF NOT EXISTS Post (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    users_id SMALLINT NOT NULL,
    content text DEFAULT NULL,
    gif_url VARCHAR(100) NULL,
    gif_alt VARCHAR(30) DEFAULT NULL,
    date_creation datetime NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (id)
    --CONSTRAINT user_post FOREIGN KEY (Users) REFERENCES Users(id)
) ENGINE = INNOD;

LOCK TABLES Post WRITE;

UNLOCK TABLES;



DROP TABLE IF EXISTS Commentaires;

CREATE TABLE IF NOT EXISTS Commentaires (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    users_id SMALLINT NOT NULL,
    comment text DEFAULT NULL,
    date_creation datetime NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (id)
    --CONSTRAINT user_comment FOREIGN KEY (Users) REFERENCES Users(id)
) ENGINE = INNODB;

LOCK TABLES Commentaires WRITE;

UNLOCK TABLES;